
apiVersion: v1
kind: Pod
metadata:
   name: app
   labels:
      app: app
spec:
    containers:      
    - name: app 
      image: taktuk/my_app:latest 
      imagePullPolicy: Always
      ports:
      - containerPort: 8080    